services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: choreography-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/choreography-planner
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_EXPIRES_IN=7d
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=eventlagbe@gmail.com
      - EMAIL_PASS=fcdc guzz fyxq rwqc
      - CLOUDINARY_CLOUD_NAME=dfvwazcdk
      - CLOUDINARY_API_KEY=558525376691438
      - CLOUDINARY_API_SECRET=5YCIYTamUiVFD6xxzgu_4fZNhpo

    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    container_name: choreography-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
